"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiFetch } from "@/src/lib/utils";

interface Profile { displayName: string; bio: string | null; region: string; mainMap: string | null; specialty: string | null }
const regions = ["NA", "EU", "ASIA", "OCE", "SA", "OTHER"];
const maps = ["ARENA", "TRACKING", "TIMED"];
export default function EditProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [busy, setBusy] = useState(false);
  useEffect(() => { apiFetch<Profile>("/api/me").then((result) => { if ("error" in result) setError(result.error.message); else setProfile(result.data); }).catch(() => setError("Could not load your player profile.")); }, []);
  async function save(event: FormEvent) { event.preventDefault(); if (!profile) return; setBusy(true); setError(""); setSaved(false); const result = await apiFetch<Profile>("/api/me", { method: "PATCH", body: JSON.stringify({ displayName: profile.displayName, bio: profile.bio || null, region: profile.region, mainMap: profile.mainMap || null, specialty: profile.specialty || null }) }); setBusy(false); if ("error" in result) setError(result.error.message); else { setProfile(result.data); setSaved(true); } }
  if (!profile) return <div className="mx-auto max-w-2xl"><h1 className="text-3xl font-black text-brand-text">Edit profile</h1>{error ? <div className="bl-alert-error mt-6">{error}</div> : <div className="mt-6 bl-card p-6 text-brand-dim">Loading profile…</div>}</div>;
  return <div className="mx-auto max-w-2xl space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-dim">Account</p><h1 className="mt-2 text-3xl font-black text-brand-text">Edit profile</h1></div><form onSubmit={save} className="bl-card space-y-5 p-6">{error && <div className="bl-alert-error">{error}</div>}{saved && <div className="bl-alert-success">Profile updated.</div>}<div className="bl-form-group"><label htmlFor="displayName" className="bl-label">Display name</label><input id="displayName" className="bl-input" minLength={2} maxLength={32} required value={profile.displayName} onChange={(event) => setProfile({ ...profile, displayName: event.target.value })} /></div><div className="bl-form-group"><label htmlFor="bio" className="bl-label">Bio</label><textarea id="bio" className="bl-input min-h-28" maxLength={500} value={profile.bio ?? ""} onChange={(event) => setProfile({ ...profile, bio: event.target.value })} /><div className="text-right text-xs text-brand-dim">{profile.bio?.length ?? 0}/500</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="bl-form-group"><label htmlFor="region" className="bl-label">Region</label><select id="region" className="bl-select" value={profile.region} onChange={(event) => setProfile({ ...profile, region: event.target.value })}>{regions.map((region) => <option key={region}>{region}</option>)}</select></div><div className="bl-form-group"><label htmlFor="mainMap" className="bl-label">Main map</label><select id="mainMap" className="bl-select" value={profile.mainMap ?? ""} onChange={(event) => setProfile({ ...profile, mainMap: event.target.value || null })}><option value="">Not set</option>{maps.map((map) => <option key={map}>{map}</option>)}</select></div></div><div className="bl-form-group"><label htmlFor="specialty" className="bl-label">Specialty</label><input id="specialty" className="bl-input" maxLength={100} value={profile.specialty ?? ""} onChange={(event) => setProfile({ ...profile, specialty: event.target.value })} /></div><div className="flex justify-end"><button className="bl-btn bl-btn-primary" type="submit" disabled={busy}>{busy ? "Saving…" : "Save changes"}</button></div></form></div>;
}
